### PR TITLE
Adding tracker component library

### PR DESCRIPTION
**Pull request by nhz2**
# Adding tracker component library

### Summary of changes
- Added instructions for installing TrackerComponentLibrary to `README.md`
- `setup_path.m` now makes sure TrackerComponentLibrary is on top of the path and alphabetical, this is needed because: 
    1. TrackerComponentLibrary expects its compiled mex files to be on the top of the path. 
    2. Matlab puts addons onto the path in some random order(at least on my mac).

### Ptest Effects
No effects.

### Testing
Follow the install instructions at the end of `README.md`, especially downloading [TrackerComponentLibrary](https://github.com/pathfinder-for-autonomous-navigation/TrackerComponentLibrary/releases/download/v4.1/TrackerComponentLibrary.mltbx) and opening it with matlab.

Unfortunately TrackerComponentLibrary doesn't come with any unit tests, but try
```
>> [a,b]=sqrtKalmanUpdate(1,1,0,1,1)

a =

    0.5000


b =

    0.7071
```
to check the install is ok.

I have only tested this on my macOS High Sierra laptop, so let me know if the installation works on your machine.

### Documentation Evidence
Edits to README.md

### CODE REVIEW

**Review by kylekrol — APPROVED** [review]
Looks good! Just out of curiosity, what platforms have we been able to test this on so far?

**Review by kylekrol — DISMISSED** [review]
Currently, I'm running into install problems on Arch Linux. Specifically, running `install.m` gives this error:

```>> install
Building with 'gcc'.
Warning: You are using gcc version '9.3.0'. The version of gcc is not supported. The version currently supported
with MEX is '6.3.x'. For a list of currently supported compilers see:
https://www.mathworks.com/support/compilers/current_release. 
> In compile_indirect (line 12)
  In make_scs (line 48)
  In CompileCLibraries (line 37)
  In install (line 8) 
Error using mex
'/home/kkrol/MATLAB
Add-Ons/Toolboxes/TrackerComponentLibrary/3rd_Party_Libraries/scs-2.0.2/scs-matlab-master/scs_indirect.mexa64' is
not a MEX file. For more information, see File is not a MEX file.
Error in compile_indirect (line 12)
eval(cmd);
Error in make_scs (line 48)
compile_indirect(flags, common_scs);
Error in CompileCLibraries (line 37)
make_scs
Error in install (line 8    CompileCLibraries;
```

Will be looking into this to hopefully get things working on my desktop at home. If @stewartaslan or someone could give this a go on Windows that would be helpful as well.

**Comment by tanishqaggarwal** [comment]
Install seemed to work fine on Windows. I ran `install.m` and MATLAB complained it couldn't find the MinGW compiler, so I installed the compiler **via the MATLAB addon** (this was important.) Then it worked out fine.

**Comment by nhz2** [comment]
`CompileCLibraries` seems like it doesn't work on Linux, so I am not going to use any of the C++ only parts of the library, fortunately most functions are also in MATLAB.

**Review by tanishqaggarwal — APPROVED** [review]

**Review by kylekrol — COMMENTED** [review]
If we're just gonna bite the bullet with linux for the time being then we can merge this in. Hopefully everyone all the team can get it working in one way or another.

**Pull request merged**
