### PR TITLE
Orbit estimator

### PR DESCRIPTION
**Pull request by nhz2**
I have integrated orbit estimation into `update_FC_state`. The estimator is implemented in `orbit_estimation` dir. The implementation still needs a lot more work before getting written in C++, specifically, trying the sequential EKF update talked about in the canx paper, and seeing what operations can be done in single or fixed precision. I also added a preliminary gps sensor model.

To test everything together, first run `config()`

Then run `run_tests` and make sure everything passes

Then run `main`, then `plot_orbit_est_errors(computer_state_leader_trajectory,main_state_trajectory)`, 
`plot_pointing_errors(main_state_trajectory)`, 
`plot_state_transitions(computer_state_leader_trajectory,main_state_trajectory)`,
`plot_gps_lock(main_state_trajectory)`, and
`plot_orbit_error(main_state_trajectory)`
To get some relavent plots

To get some test of only the estimator run 
`test_orb_run_estimator` and `test_orb_run_estimator_cdgps`

### CODE REVIEW

**Review by kylekrol — APPROVED** [review]
Honestly this PR is so huge going through all of it in a reasonable amount of time doesn't seem to practical lol Overall structure looks good and I was able to get everything running locally so I'm approving.

**Comment by nhz2** [comment]
@tanishqaggarwal  I'm adding you as a reviewer as well. There are a lot of updated files in this PR,  a lot of them are from @srutiv  old `true_orbit_propagator` branch, adding in a better GPS sensor model, orbit propagator prototypes, and testing. For changes to flight software, look at `update_FC_state`. For that, there are new actuator commands that the flight computer uses to try and downlink it current orbit estimate. Also, I added the obit estimator interface near the beginning of the function.

**Review by tanishqaggarwal — APPROVED** [review]
Looks good to me. This might break ptest a little bit since some variable names got flopped around, but I'll fix them case-by-case once this PR is merged in.

**Comment by kylekrol** [comment]
I'll starting working off of this for rendezvous code then and rebase off master once it gets merged.

**Pull request merged**
