### PR TITLE
Gravity model

### PR DESCRIPTION
**Pull request by nhz2**
C++ Gravity model

### CODE REVIEW

**Comment by nhz2** [comment]
#65

**Comment by nhz2** [comment]
I put all of the files in the `geograv` directory in `psim` temporarily to help debugging.

The main gravity function and the definition of the `Coeff` class is in `geograv.hpp`

`EGM96.hpp` has the coefficients for the 360x360 egm96 model.

`teensy_test` is an arduino sketch to run on the teensy.

`gravmodelgen.py` is a python script to convert text files with coefficients to the c++ header files with coefficients. 

`main.cpp` is a the test file for running on desktop.
## Installation

First install [geographiclib](https://geographiclib.sourceforge.io/html/index.html):
On mac you can just `brew install geographiclib`
Then run `/usr/local/sbin/geographiclib-get-gravity all` to install all of the gravity models.

 To run the tests,
First open terminal in the `geograv` directory, then run the following commands:
`mkdir build`
`cd build`
`cmake ..`
`make`
`./TestGeoGrav`

To generate new coefficient header files, use `gravmodelgen.py`, for example:
`python gravmodelgen.py -f egm96 -n 360 -o EGM96.hpp -r 6378137.0 -u 0.3986004418e15`
and
`python gravmodelgen.py -f egm96 -n 20 -o EGM96_20.hpp -r 6378137.0 -u 0.3986004418e15`

**Comment by nhz2** [comment]
A max order and degree 20 model with numerical precision of about 1E-11 m/s^2 runs on the teensy 3.6 in about 300 microseconds.

**Comment by kkrol27** [comment]
Looks pretty good to me. Just curious, you mentioned dropping this stuff in the geograve subdirectory was temporary. Would you want to integrate everything into the existing platformio structure and drop cmake yourself or would you want me to take care of that after the PR goes through? Doesn't really matter to me.

**Review by kylekrol — COMMENTED** [review]
Looks pretty good to me. Just curious, you mentioned dropping this stuff in the geograve subdirectory was temporary. Would you want to integrate everything into the existing platformio structure and drop cmake yourself or would you want me to take care of that after the PR goes through? Doesn't really matter to me.

**Comment by nhz2** [comment]
The python script and model files can probably stay in the `geograv` subdirectory unless you think there is a better place for them. You can integrate the gravity model with the other C++ environmental models after the PR merge.

**Review by kylekrol — DISMISSED** [review]

**Review by kylekrol — APPROVED** [review]

**Pull request merged**
